name = "cgk"
description = "Computational Geometry Kernel"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded"]

project-files = ["gnat/cgk_primitives.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true
